description = "Show listener status."

prompt = """
!{
  if [ -f .tmp/gemini-listen.pid ]; then
    read PID < .tmp/gemini-listen.pid
    if [ -n "$PID" ]; then
      echo "Listener: http://localhost:8765/event"
      echo "PID: $PID"
      echo "Logs: .tmp/gemini-listen.log"
      exit 0
    else
      echo "Not running (stale PID file found: .tmp/gemini-listen.pid with PID $PID)"
      exit 0
    fi
    # PID file exists but process isn't alive
  fi
  echo "Not running"
}
Return the three lines above exactly.
"""