description = "Stop webhook listener (in sandbox)"

prompt = """
!{
  echo "Attempting to shut down webhook listener..."
  curl -s -X POST http://localhost:8765/shutdown
  if [ $? -eq 0 ]; then
    echo "Webhook listener shutdown request sent successfully."
  else
    echo "Webhook listener not running or failed to send shutdown request."
  fi

  if [ -f .tmp/gemini-listen.pid ]; then
    read -r PID < .tmp/gemini-listen.pid
    if [ -n "$PID" ]; then # Check if PID is not empty
      echo "Found PID $PID in .tmp/gemini-listen.pid. Attempting to kill process..."
      kill "$PID"
      if [ $? -eq 0 ]; then
        echo "Process $PID killed successfully."
      else
        echo "Failed to kill process $PID. It might not be running."
      fi
    else
      echo "PID file .tmp/gemini-listen.pid is empty."
    fi
    rm .tmp/gemini-listen.pid
    echo "Removed PID file .tmp/gemini-listen.pid"
  else
    echo "PID file .tmp/gemini-listen.pid not found."
  fi
}
Return the line above exactly.
"""
